# permissions for end users to edit parents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: parent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: otel-sample-controller
    app.kubernetes.io/part-of: otel-sample-controller
    app.kubernetes.io/managed-by: kustomize
  name: parent-editor-role
rules:
- apiGroups:
  - otel.zoetrope.github.io
  resources:
  - parents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.zoetrope.github.io
  resources:
  - parents/status
  verbs:
  - get
